create database empdata;
CREATE TABLE EMP(EMPID INT,EMPNAME VARCHAR(30),EMPAGE INT);
SELECT * FROM EMP;
INSERT INTO EMP VALUES(1234, 'WARD', 12);
INSERT INTO EMP VALUES(4567, 'ALLEN', 20);
INSERT INTO EMP VALUES(8910, 'WARD', 24);
ALTER TABLE EMP ADD EMPADD VARCHAR(15);
ALTER TABLE EMP DROP EMPADD;
DELETE FROM EMP WHERE EMPID=1234;
DROP TABLE EMP;



